export const NY_CATEGORIES = {
  Arts: "Arts",
  Automobiles: "Automobiles",
  Autos: "Autos",
  Blogs: "Blogs",
  Books: "Books",
  Booming: "Booming",
  Business: "Business",
  BusinessDay: "Business Day",
  Corrections: "Corrections",
  CrosswordsGames: "Crosswords & Games",
  CrosswordsGamesAlt: "Crosswords/Games",
  DiningWine: "Dining & Wine",
  DiningAndWine: "Dining and Wine",
  EditorsNotes: "Editors' Notes",
  Education: "Education",
  FashionStyle: "Fashion & Style",
  Food: "Food",
  FrontPage: "Front Page",
  Giving: "Giving",
  GlobalHome: "Global Home",
  GreatHomesDestinations: "Great Homes & Destinations",
  GreatHomesAndDestinations: "Great Homes and Destinations",
  Health: "Health",
  HomeGarden: "Home & Garden",
  HomeAndGarden: "Home and Garden",
  InternationalHome: "International Home",
  JobMarket: "Job Market",
  Learning: "Learning",
  Magazine: "Magazine",
  Movies: "Movies",
  Multimedia: "Multimedia",
  MultimediaPhotos: "Multimedia/Photos",
  NYRegion: "N.Y. / Region",
  NYRegionAlt: "N.Y./Region",
  NYRegionAlt2: "NYRegion",
  NYTNow: "NYT Now",
  National: "National",
  NewYork: "New York",
  NewYorkAndRegion: "New York and Region",
  Obituaries: "Obituaries",
  Olympics: "Olympics",
  Open: "Open",
  Opinion: "Opinion",
  PaidDeathNotices: "Paid Death Notices",
  PublicEditor: "Public Editor",
  RealEstate: "Real Estate",
  Science: "Science",
  Sports: "Sports",
  Style: "Style",
  SundayMagazine: "Sunday Magazine",
  SundayReview: "Sunday Review",
  TMagazine: "T Magazine",
  TStyle: "T:Style",
  Technology: "Technology",
  ThePublicEditor: "The Public Editor",
  TheUpshot: "The Upshot",
  Theater: "Theater",
  TimesTopics: "Times Topics",
  TimesMachine: "TimesMachine",
  TodaysHeadlines: "Today's Headlines",
  Topics: "Topics",
  Travel: "Travel",
  US: "U.S.",
  Universal: "Universal",
  UrbanEye: "UrbanEye",
  Washington: "Washington",
  WeekInReview: "Week in Review",
  World: "World",
  YourMoney: "Your Money",
};
